### ISSUE TITLE
Crashing Node-RED Instance

### ISSUE THREAD

**Issue by My-Random-Thoughts** [fatoldsun00/node-red-contrib-sftpco#1]
Hey,

I am getting the following crash when trying to upload multiple files:

`25 Jul 12:05:02 - [red] Uncaught Exception:`
`25 Jul 12:05:02 - [error] Error: end: No SFTP connection available`
`.    at formatError (/data/node_modules/ssh2-sftp-client/src/utils.js:62:18)`
`.    at Object.haveConnection (/data/node_modules/ssh2-sftp-client/src/utils.js:627:20)`
`.    at /data/node_modules/ssh2-sftp-client/src/index.js:1361:19`
`.    at new Promise (<anonymous>)`
`.    at SftpClient.end (/data/node_modules/ssh2-sftp-client/src/index.js:1338:12)`
`.    at SFTPNode._inputCallback (/data/node_modules/node-red-contrib-sftpco/node-red-sftpco.js:156:11)`
`.    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`
`25 Jul 12:05:03 - [info] `

It has been working in the past, but has stopped recently - I think due to a NPM version update

OS: Linux 5.13.0-52-generic x86_64
NR: node-red-docker@3.0.1
NPM: 8.13.2
NodeJS: 18.6.0

**Comment by My-Random-Thoughts** [comment]
I should add more detail.  :)
I am trying to PUT files onto my Synology NAS.
Other copied of this node works fine when I am using GET from devices (router backups, etc)

**Comment by fatoldsun00** [comment]
Hi,

You can try to update ssh2-sftp-client include in this node. I not maintain this node anymore, but if you test this solution you can make a PR au updated package.json (5.1.2 in package but [9.0.2](https://github.com/theophilusx/ssh2-sftp-client/tags) is available )

**Comment by My-Random-Thoughts** [comment]
I have updated the package in your node, but I am still getting the same issue.  :(
Thanks anyway

**Comment by fatoldsun00** [comment]
Maybe try to open issue on ssh2-sftp-client github page. I had check on issue, some people have the same issue but nothing revelant

**Comment by sahaine** [comment]
I was having a similar issue, a combination of updating ssh2-sftp-client and a small code change to ensure the client is rebuilt on each event (PR submitted), and mine appears to be stable once more...  npm install ssh2-sftp-client
